### ISSUE TITLE
Can't pass async function to v.extend 

### ISSUE THREAD

**Issue by hulyo-firmansyah** [ratiw/Validator#40]
### Can't pass async function to v.extend 

`await v.extend('unique', async(name, value, params) => {
                let callback = Product.query()
                let SKUPayload = await callback.where('sku', 'LIKE', `${value}`).select()
                if (SKUPayload.length > 0) return true
               return false
            }, ':attr is not unique');`

i'm trying to pass async function to v.extend and it always return false

**Comment by jfstn** [comment]
Hello 👋 

Validator was not written with async/away in mind. You can extend the functionality but it must be something synchronous.

Thank you @hulyo-firmansyah
